M48
; DRILL file {KiCad 9.0.1} date 2025-04-28T02:05:27+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-28T02:05:27+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X168.338Y-112.81
X168.338Y-118.59
T2
X136.7Y-132.1
X136.8Y-97.0
X171.7Y-97.1
X171.7Y-132.1
M30
